#!/usr/bin/env bash

if [ -e ./p42.yaml ]; then
  echo p42: directory already contains a p42.yaml file
  exit -1
fi

name=$(basename $(pwd))
repo=$(dirname \
      $(git ls-remote --get-url |\
        awk -F : '{print $2}'))

read -e -p "Application name [$name]: " input
name=${input:-$name}

read -e -p "Organization repository [$repo]: " input
repo=${input:-$repo}

cat << EOF > ./p42.yaml
name: ${name}
repo: ${repo}
EOF
