#!/usr/bin/env bash

_add() {
  local name="${1}" path="${2-${1}}"
  if [ ! -d "${mixins}/${path}" ]; then
    abort "invalid mixin: <${path}>"
  fi
  mixin="./run/${name}"
  mkdir -p "${mixin}"
  cp -R "${mixins}/${path}/run" "${mixin}"
  p42 interview "${mixins}/${path}/interview.yaml" > "${mixin}/config.yaml"
}

_rm() {
  local name="${1}"
  if [ -d "./run/${name}" ]; then
    rm -rf "./run/${name}"
  fi
}

_help() {
  echo "help!"
}

action=$1; shift
_${action} ${@}
