#!/usr/bin/env bash

# Usage: p42 build [<component>...]
# Summary: Build one or more components for an application.
# Help: Build one or more components for an application.
#
#    p42 build www
#

include decorators

for part in $parts; do decorator ${part}; done
