#!/usr/bin/env bash

include 'test'
include options
include commands
include aws
include dns

test_create_repo() {
  run_test create_repo blurb9-api
}

test_set_security_groups() {
  run_test set_security_groups \
    vpc=test-vpc-00 \
    name=test-instance-00 \
    groups='default docker-machine'
}

test_get_registry_domain() {
  run_test get_registry_domain
}

test_dns_a() {
  run_test dns_a \
    cluster='violent-aftermath' \
    name='test.com' \
    ip='192.168.0.42' \
    comment='this is a test'
}

test_get_elb() {
  run_test get_elb 'violent-aftermath'
}

test_register_with_elb() {
  run_test register_with_elb \
    instance_id='test-instance-00' \
    cluster='vodka-martini'
}

declare test $(options 'test' ${@})

dry_run=true
clusters="${share}/test/clusters"

if [ -n "${test}" ]; then
  "test_${test}"
else
  run_tests
fi
