#!/usr/bin/env bash

if [ ! -e ./p42.yaml ]; then
  echo p42: missing p42.yaml file
  echo p42: try running: p42 init
  exit -1
fi

name=$(yaml ./p42.yaml name)
repo=$(yaml ./p42.yaml repo)

if [ $# -gt 0 ]; then
  containers="$@"
else
  if [ ! -d ./launch ]; then
    echo p42: nothing to stop
    exit
  fi
  containers=$(ls ./launch)
fi

# TODO: what if the swarm master dies?
eval $(docker env --swarm swarm-00)

running=$(docker ps)

for container in $containers; do
  label=$name-$container
  id=$(echo $running | grep $label | awk '{ print $1 }')
  if [ $id ]; then
    echo Stopping $label container...
    docker stop $id && docker rm $id
  fi
done
