#!/usr/bin/env bash

include machine
include aws
include docker
include context

declare "$(get_elb ${cluster})"

_pull() {
  local cluster image
  local "${@}"

  echo "Pulling image '${image}' onto Swarm nodes..."

  for node in $(list_swarm_nodes "${cluster}"); do
    echo "- ${node}"
    docker_env "${node}"
    docker_login
    docker pull ${registry}/${image}:latest
  done
}

_run() {
  local part image config count subdomains
  local "${@}"

  image="${app}-${part}"
  config="${run}/${part}/config.yaml"
  count=$(yaml get "${config}" count)
  subdomains=$(yaml get "${config}" subdomains)

  # For each swarm node, we need to make sure it has a
  # copy of the image. For a private registry, this
  # doesn't happen automatically, so we have to authenticate
  # to each and pull.

  _pull \
    cluster="${cluster}" \
    image="${image}"

  swarm_env "${cluster}"
  docker_login

  for (( i = 0 ; i < ${count:=1} ; i++ )); do
    instance="${part}-$(printf '%02d' $i)"
    container="${app}-${instance}"

    echo "Starting '${image}' container '${container}'..."

    if [ -n "${subdomains}" ]; then
      port_option="-p 80:80"
    else
      port_option="-P"
    fi

    docker_run \
      name="${container}" \
      image="${registry}/${image}:latest" \
      options="${port_options}"

    local "$(docker_inspect ${container})"
    local "$(get_instance ${name})"

    # Add private A record for container
    dns_a \
      name="${container}" \
      ip="${ip}" \
      comment="Added by p42 for stack '${cluster}'"

    # save the list of containers so we can set up
    # DNS SRV records later / we only need to do this
    # if discovery is set in the config
    discovery="$(yaml get "${config}" discovery)"
    if [ -n "${discovery}" ]; then
      targets="${targets} ${container} ${port}"
    fi

    # Add to ELB, if applicable, based on subdomains
    if [ -n "${subdomains}" ]; then

      register_instance_with_elb \
        cluster="${cluster}" \
        instance="${id}"

      for subdomain in ${subdomains}; do
          echo "Adding '${subdomain}' alias for ELB..."
          dns_alias \
            subdomain="${subdomain}" \
            domain="${domain}" \
            comment="Added by p42 for stack '${cluster}'"
      done
    fi
  done

  for protocol in ${discovery}; do
    dns_srv \
      protocol="${protocol}" \
      public="${component}" \
      targets="${targets}" \
      comment="Added by p42 for stack '${cluster}'"
  done

}

for part in $parts; do
  _run "${part}"
done
