#!/usr/bin/env bash

if [ ! -e ./p42.yaml ]; then
  echo p42: missing p42.yaml file
  echo p42: try running: p42 init
  exit -1
fi

name=$(yaml ./p42.yaml name)
repo=$(yaml ./p42.yaml repo)

if [ $# -gt 0 ]; then
  images="$@"
else
  if [ ! -d ./launch ]; then
    echo p42: nothing to build
    exit
  fi
  images=$(ls ./launch)
fi

# TODO: what if the swarm master dies?
eval $(docker env --swarm swarm-00)

for image in $images; do
  label=$name-$image
  echo Building $repo/$label image...
  docker build \
    -t $repo/$label \
    -f launch/$2/Dockerfile \
  echo Pushing $repo/$label image...
  sleep 2
  docker push $repo/$label
done
