#!/usr/bin/env bash

action=$1
shift

case "$action" in

  add)
    name=$1
    shift
    path=$1
    shift

    directory=$(mktemp -d "${TMPDIR:-/tmp}/p42.XXXXXXXXX")

    git clone $path $directory

    mkdir -p ./launch/$name
    cp -R $directory/template/ ./launch/$name/
    if [ -x $directory/bin/interview ]; then
      _MIXIN_ROOT=$directory \
      $directory/bin/interview > ./launch/$name/config.yaml
    fi
    ;;

  esac
