#!/usr/bin/env bash

# Usage: p42 run [<component>]
# Summary: Build images and start application containers.
# Help: Build images and start application containers.
# You can run the entire application or just a given set of components.
#
#     p42 run
#     p42 run www redis
#

if [ $# -gt 0 ]; then
  components="$@"
else
  if [ ! -d ./launch ]; then
    echo p42: nothing to run
    exit
  fi
  components=$(ls ./launch)
fi

p42 build $components
p42 start $components
