#!/usr/bin/env bash

# Usage: p42 ps
# Summary: List deployed containers and their IP/port.
# Help: List deployed containers and their IP/port.

# TODO: what if the swarm master dies?
eval $(docker-machine env --swarm swarm-00)
docker ps --format '{{ .Names }} {{ .Ports }}'
