#!/usr/bin/env bash


include docker
include context

# TODO: how to get a list of parts into the environment
#
#   declare "$(load_context)"
#
# or put all this inside a function?

swarm_env "${cluster}"

for part in ${parts}; do
  stop_containers $(list_containers "${part}")
done
